In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

rng = np.random.default_rng(7)
n = 80

cities = ['Chennai', 'Coimbatore', 'Madurai', 'Trichy',
          'Salem', 'Erode', 'Vellore', 'Kanyakumari']
p = [0.28, 0.24, 0.18, 0.12, 0.08, 0.05, 0.03, 0.02]

df = pd.DataFrame({
    'age': rng.integers(25, 80, n),
    'gender': rng.choice(['Male', 'Female'], n),
    'city': rng.choice(cities, n, p=p),
    'treatment': rng.choice(
        ['Radiotherapy', 'Chemotherapy', 'Surgery', 'Immunotherapy'],
        n, p=[0.4, 0.3, 0.2, 0.1]),
    'stay_days': rng.integers(1, 15, n),
})
df['readmitted'] = rng.integers(0, 2, n)

X = df.drop(columns='readmitted')
y = df['readmitted']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.25, random_state=32
)

In [2]:
print('X_train.shape',X_train.shape)

print('X_test.shape',X_test.shape)

print('df.shape',df.shape)

X_train.shape (60, 5)
X_test.shape (20, 5)
df.shape (80, 6)

In [3]:
print(df.dtypes)

df.select_dtypes(include='str')   #gender	city	treatment

df.isna().sum()   # 0 in all

age           int64
gender          str
city            str
treatment       str
stay_days     int64
readmitted    int64
dtype: object

age           0
gender        0
city          0
treatment     0
stay_days     0
readmitted    0
dtype: int64

In [4]:
X_train['city'].value_counts(dropna=False)

city
Chennai       17
Coimbatore    13
Madurai       10
Trichy         9
Salem          5
Erode          3
Vellore        3
Name: count, dtype: int64

In [5]:
X_test['city'].value_counts(dropna=False)

city
Coimbatore     9
Madurai        4
Erode          2
Chennai        2
Kanyakumari    1
Vellore        1
Trichy         1
Name: count, dtype: int64

In [6]:
set(X_test)-set(X_train)

set()

In [7]:
import pandas as pd

df = pd.DataFrame({
    'age':     [30, 45, 28, 52, 39],
    'job':     ['admin', 'technician', 'student', 'retired', 'admin'],
    'marital': ['single', 'married', 'single', 'married', 'divorced'],
    'housing': ['yes', 'no', 'yes', 'no', 'yes'],
    'y':       ['no', 'yes', 'no', 'yes', 'no'],
})

In [10]:
pd.get_dummies(df,drop_first=True,dtype=int)

,age,job_retired,job_student,job_technician,marital_married,marital_single,housing_yes,y_yes
0,30,0,0,0,0,1,1,0
1,45,0,0,1,1,0,0,1
2,28,0,1,0,0,1,1,0
3,52,1,0,0,1,0,0,1
4,39,0,0,0,0,0,1,0

In [ ]:
bank=pd.read_csv(r'C:\Users\VP\Downloads\bank.csv')
from sklearn.model_selection import train_test_split  
from sklearn.preprocessing import OneHotEncoder
from sklearn.impute import SimpleImputer

y=bank['deposit']
x=bank.drop(columns='deposit')
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20,random_state=42)

text=x_train.select_dtypes(include='str').columns
number=x_train.select_dtypes(include=['int','float']).columns

si=SimpleImputer(strategy='most_frequent')
for i in text:
    x_test[i]=x_test[i].replace('unknown',np.nan)
    x_train[i]=x_train[i].replace('unknown',np.nan)


x_train[text]=si.fit_transform(x_train[text])
x_test[text]=si.transform(x_test[text])

In [ ]:
ohe=OneHotEncoder(handle_unknown='ignore', sparse_output=False)
train_array=ohe.fit_transform(x_train[text])
train_ohe = pd.DataFrame(train_array,
                         columns=ohe.get_feature_names_out(text),
                         index=x_train.index)

In [104]:
x_train_final=pd.concat([train_ohe,x_train[number]],axis=1)

In [105]:
x_train_final

,job_admin.,job_blue-collar,job_entrepreneur,job_housemaid,job_management,job_retired,job_self-employed,job_services,job_student,job_technician,...,poutcome_failure,poutcome_other,poutcome_success,age,balance,day,duration,campaign,pdays,previous
3955,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,1.0,0.0,0.0,28,5741,10,1042,5,200,3
11150,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,34,355,21,314,3,-1,0
5173,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,48,201,10,594,1,91,1
3017,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,53,1961,15,351,1,-1,0
2910,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,53,1624,11,166,3,97,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5734,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,47,761,11,80,2,-1,0
5191,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,1.0,28,159,16,449,2,33,4
5390,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,0.0,35,1144,20,197,13,-1,0
860,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,51,746,25,372,5,-1,0
7270,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,30,2,23,269,1,-1,0

In [115]:

test_array=ohe.transform(x_test[text])
df_test_text=pd.DataFrame(test_array,columns=ohe.get_feature_names_out(text),index=x_test.index)
final_test_array=pd.concat([df_test_text,x_test[number]],axis=1)

In [116]:
final_test_array

,job_admin.,job_blue-collar,job_entrepreneur,job_housemaid,job_management,job_retired,job_self-employed,job_services,job_student,job_technician,...,poutcome_failure,poutcome_other,poutcome_success,age,balance,day,duration,campaign,pdays,previous
5527,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,65,744,5,182,1,-1,0
4541,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,38,1627,16,1323,9,-1,0
1964,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,35,4963,14,456,1,300,1
5007,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,47,8229,8,784,2,-1,0
8928,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,0.0,35,1473,12,84,3,-1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
376,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,46,926,7,385,5,-1,0
5544,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,0.0,49,230,8,96,1,-1,0
10749,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,0.0,53,431,5,55,1,328,1
3881,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,48,926,12,504,2,178,10
6786,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,34,1636,6,136,1,521,2

In [117]:
x_train_final

,job_admin.,job_blue-collar,job_entrepreneur,job_housemaid,job_management,job_retired,job_self-employed,job_services,job_student,job_technician,...,poutcome_failure,poutcome_other,poutcome_success,age,balance,day,duration,campaign,pdays,previous
3955,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,1.0,0.0,0.0,28,5741,10,1042,5,200,3
11150,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,34,355,21,314,3,-1,0
5173,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,48,201,10,594,1,91,1
3017,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,53,1961,15,351,1,-1,0
2910,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,53,1624,11,166,3,97,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5734,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,47,761,11,80,2,-1,0
5191,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,1.0,28,159,16,449,2,33,4
5390,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,0.0,35,1144,20,197,13,-1,0
860,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,51,746,25,372,5,-1,0
7270,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,30,2,23,269,1,-1,0